name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adc0b5a791f8fa487b44afe2d01a94a9390f412f2fddc35bf8d3c4dd094aba1e"

[versions]
minecraft = "1.20.2"
quilt = "0.23.1"
